#!/usr/bin/env bash
#
# Solitude Theme Kit installer
# - Installs the standalone solitude GTK theme (replaces adw-gtk3)
# - Ensures thpm (AUR) is present (live theming engine)
# - Installs the hand-made Kvantum "solitude" style
# - Sets GTK theme + color-scheme
# - Copies qt6ct/Kvantum/gtk configs to /root for pkexec GUI apps
#
# Run AFTER selecting the solitude theme in Omarchy (so thpm has rendered
# the qt6ct color scheme + app themes into your user config).

set -euo pipefail

KIT="$(cd "$(dirname "$0")" && pwd)"
GTK_PKG="$(ls "$KIT"/solitude-gtk-theme/solitude-gtk-theme-*.pkg.tar.gz 2>/dev/null | head -n1)"

echo "==> Solitude Theme Kit installer"
echo "    kit: $KIT"

# 1. GTK theme (GTK2/3/4) — replaces adw-gtk3
if [[ -z "${GTK_PKG:-}" ]]; then
  echo "!! solitude-gtk-theme package not found; building from source..."
  ( cd "$KIT/solitude-gtk-theme" && PKGEXT='.pkg.tar.gz' makepkg -f )
  GTK_PKG="$(ls "$KIT"/solitude-gtk-theme/solitude-gtk-theme-*.pkg.tar.gz | head -n1)"
fi
echo "==> Installing solitude-gtk-theme (GTK2/3/4)..."
sudo pacman -U --needed "$GTK_PKG"

# 2. thpm (AUR) — active theming engine (renders qt6ct + app themes)
if ! command -v thpm >/dev/null 2>&1; then
  echo "==> Installing thpm (AUR)..."
  yay -S --needed thpm
else
  echo "==> thpm already installed"
fi

# 3. Kvantum solitude (hand-made; thpm does NOT generate this)
echo "==> Installing Kvantum solitude..."
mkdir -p "$HOME/.config/Kvantum/solitude"
cp -r "$KIT/Kvantum/solitude/." "$HOME/.config/Kvantum/solitude/"
printf '[General]\ntheme=solitude\n' > "$HOME/.config/Kvantum/kvantum.kvconfig"

# 4. GTK theme setting
echo "==> Setting GTK theme to solitude..."
gsettings set org.gnome.desktop.interface gtk-theme solitude
gsettings set org.gnome.desktop.interface color-scheme prefer-dark

# 5. Root theming for pkexec GUI apps (GParted, btrfs-assistant, ...)
echo "==> Installing root theming for pkexec apps..."
sudo mkdir -p /root/.config/gtk-3.0 /root/.config/qt6ct/colors /root/.config/Kvantum/solitude
sudo bash -c 'cat > /root/.config/gtk-3.0/settings.ini' <<'EOF'
[Settings]
gtk-theme-name=solitude
gtk-icon-theme-name=Papirus-Dark
gtk-color-scheme=prefer-dark
EOF
sudo cp -r "$KIT/Kvantum/solitude/." /root/.config/Kvantum/solitude/
sudo bash -c 'printf "[General]\ntheme=solitude\n" > /root/.config/Kvantum/kvantum.kvconfig'
# copy user's rendered qt6ct (generated by thpm from solitude) to root
if [[ -d "$HOME/.config/qt6ct" ]]; then
  sudo cp -r "$HOME/.config/qt6ct/." /root/.config/qt6ct/
fi
# copy user's gtk.css palette override to root (if present)
if [[ -f "$HOME/.config/gtk-3.0/gtk.css" ]]; then
  sudo cp "$HOME/.config/gtk-3.0/gtk.css" /root/.config/gtk-3.0/gtk.css
fi

echo
echo "==> Done. Solitude is installed:"
echo "   - GTK theme : solitude (GTK2/3/4)"
echo "   - Qt style  : Kvantum solitude"
echo "   - thpm      : active (renders qt6ct + app themes from solitude)"
echo "   - root apps : themed via /root/.config"
echo "   If you just selected the Omarchy solitude theme, re-login (or restart"
echo "   the shell) so the qt6ct palette + Kvantum fully apply."
