context.modules = [
    { name = libpipewire-module-parametric-equalizer
      args = {
          equalizer.filepath = "/home/linuxer/.config/pipewire/soundcore.txt"
          equalizer.description = "Soundcore R60i NC EQ Sink"
          audio.channels = 2
          audio.position = [FL, FR]
          capture.props = {
              node.name = "eq_input"
              media.class = "Audio/Sink"
              
              # Locks the EQ input node timetable
              node.quantum = 2048/48000
              node.force-rate = 48000
          }
          playback.props = {
              node.name = "eq_output"
              node.passive = true
              
              # Locks the EQ output node timetable
              node.quantum = 2048/48000
              node.force-rate = 48000
          }
      }
    }
]

