context.properties = {
    # Force system-wide sampling speed
    default.clock.rate          = 48000
    
    # Strictly freeze the buffer size to 2048 to prevent performance fluctuations
    default.clock.quantum       = 2048
    default.clock.min-quantum   = 2048
    default.clock.max-quantum   = 2048
    default.clock.quantum-limit = 2048
}

