################
profile=fast

#### =========================
#### VIDEO / GPU (STABLE WAYLAND SETUP)
#### =========================
vo=gpu-next
gpu-api=opengl
gpu-context=wayland
hwdec=vaapi
hwdec-codecs=all
wayland-internal-vsync=no


#### =========================
#### GENERAL SETTINGS
#### =========================
force-window=immediate
deinterlace=no
drag-and-drop=replace
keep-open=yes
save-position-on-quit=yes
video-aspect-override=16:9
deband=no

#### =========================
#### AUDIO (7.1 VIRTUAL SURROUND PATHWAY)
#### =========================
volume-max=200
audio-channels=8
audio-device=pipewire
audio-pitch-correction=yes
alang=eng,en,enUS,en-US,english,english-us,english-US

#### =========================
#### CLEAN UI
#### =========================

osc=no
osd-bar=no
border=no
osd-font-size=15

#### =========================
####  YTDLP SUPPORT
#### =========================

ytdl-format="bv*[height<=720][vcodec^=avc1]+ba[acodec=opus]/bv*[height<=720][vcodec^=avc1]+ba/best"
ytdl-raw-options=yes-playlist=,write-sub=,embed-subs=,write-auto-sub=
ytdl-raw-options-append=cookies-from-browser=chromium
script-opts-add=ytdl_hook-ytdl_path=yt-dlp

#### =========================
#### STREMIO + YTDLP CACHING
#### =========================

cache=yes
demuxer-max-bytes=150M
demuxer-readahead-secs=120
cache-secs=120

#### =========================
#### LOCAL STREAM EXTRA BUFFERING PROFILE
#### =========================
# Intercepts any local streaming server (Stremio, TorrServer, or WebTorrent)
[protocol.http]
profile-cond=string.match(url, "localhost:") ~= nil
demuxer-max-bytes=800MiB
demuxer-max-back-bytes=200MiB
demuxer-readahead-secs=300
cache-secs=300

# ==========================================
# FORCE SUBTITLES REGARDLESS OF INHERITANCE
# ==========================================
[default]
sub-auto=all
slang=eng,en,english,eng-us,engUS,eng-US,en-us,enUS,en-US,english-us,english-US

# This forces mpv to strip embedded font styles and use yours
sub-ass-override=force

# Visual styling properties
sub-scale=0.42
sub-font-size=45
sub-border-size=2
sub-shadow-offset=1
sub-margin-y=40

# Critical layout fixes
sub-ass-force-margins=yes
sub-ass-scale-with-window=yes
embeddedfonts=yes

# Font configuration
sub-font="Slate For OnePlus"

# Path scanning for external tracks
sub-file-paths-append=ass
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles
