# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = sleep 3 && jamesdsp --tray
exec-once =  sleep 10 && ~/.config/hypr/scripts/weather_notification.sh
exec-once = hyprctl setcursor WinSur 16


