# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
bindd = SUPER, N, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Mpv, exec, uwsm app -- /usr/bin/mpv --player-operation-mode=pseudo-gui --
bindd = SUPER, D, Discord, exec, uwsm app -- /usr/lib/vesktop/vesktop
bindd = SUPER SHIFT, T, AyuGram, exec, AyuGram --
bindd = SUPER, Y, Nvtop, exec, omarchy-launch-tui nvtop
bindd = SUPER, Q, Torrent, exec, uwsm app -- /usr/bin/qbittorrent
bindd = SUPER, Z, Dolphin, exec, uwsm app -- /usr/bin/dolphin
bindd = SUPER, H, Helium, exec, uwsm app -- /opt/helium-browser-bin/helium --ozone-platform=wayland
bindd = SUPER CTRL, M, Music, exec, omarchy-launch-tui kew
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-tui rmpc
bindd = SUPER SHIFT, Y, Youtube, exec, omarchy-launch-tui youtube-tui
bindd = SUPER, R, Explorer, exec, omarchy-launch-tui spf
bind = SUPER SHIFT, A, exec, foot -e bash -ic root-jump



# Brightness control with arrow keys
bind = SUPER, Up, exec, brightnessctl set +1%
bind = SUPER, Down, exec, brightnessctl set 1%-


# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, Space
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Replace the existing togglefloating bind for Mpv
bind = SUPER, E, exec, ~/.config/hypr/scripts/togglefloating_resize.sh



