name = "Everpuccin"
background = "#181B1B"
surface = "#181B1B"
text = "#E7DECD"
accent = "#A7C080"
danger = "#E67E80"
muted = "#181B1B"
highlight = "#2D353B"
border = "#2D353B"
dim_text = "#859289"
syntax_keyword = "#D699B6"
syntax_string = "#A7C080"
syntax_constant = "#E69875"
syntax_type = "#83C092"
syntax_preprocessor = "#DBBC7F"