#!/usr/bin/env sh

# Directory where to store temporary data
TMP_DIR="/tmp/rmpc"

# Ensure the directory is created
mkdir -p "$TMP_DIR"

# Where to temporarily store the album art received from rmpc
ALBUM_ART_PATH="$TMP_DIR/notification_cover.jpg"

# Path to fallback album art if no album art is found by rmpc/mpd
# Change this to your needs
DEFAULT_ALBUM_ART_PATH="$TMP_DIR/default_album_art.jpg"

# Get current song info
SONG_INFO=$(rmpc song)
ARTIST=$(echo "$SONG_INFO" | jq -r '.metadata.artist // .metadata.album_artist // "Unknown Artist"')
TITLE=$(echo "$SONG_INFO" | jq -r '.metadata.title // .file | split("/")[-1] | split(".")[0] // "Unknown Title"')

# Save album art of the currently playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
    # No album art available, send notification without icon
    notify-send "Now Playing" "$ARTIST - $TITLE"
else
    # Send notification with album art
    notify-send -i "${ALBUM_ART_PATH}" "Now Playing" "$ARTIST - $TITLE"
fi
