# Cache stream directly to your media partition space
path=/mnt/media

# Engine configurations
maxConns=100
port=8888
utp=no
dht=yes
lsd=yes
downloadLimit=-1
uploadLimit=-1

# Use the exact node binary managed by mise
node_path=/home/linuxer/.local/share/mise/installs/node/22.23.0/bin/node
