[Icon Theme]
Name=Papirus Espresso
Comment=Espressuccin ink recoloring of Papirus (folders only)
Inherits=Papirus

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

# Sizes and contexts
Directories=16x16/places,16x16@2x/places,22x22/places,22x22@2x/places,24x24/places,24x24@2x/places,32x32/places,32x32@2x/places,48x48/places,48x48@2x/places,64x64/places,64x64@2x/places,96x96/places,128x128/places

[16x16/places]
Size=16
Scale=1
Context=Places
Type=Fixed

[16x16@2x/places]
Size=16
Scale=2
Context=Places
Type=Fixed

[22x22/places]
Size=22
Scale=1
Context=Places
Type=Fixed

[22x22@2x/places]
Size=22
Scale=2
Context=Places
Type=Fixed

[24x24/places]
Size=24
Scale=1
Context=Places
Type=Fixed

[24x24@2x/places]
Size=24
Scale=2
Context=Places
Type=Fixed

[32x32/places]
Size=32
Scale=1
Context=Places
Type=Fixed

[32x32@2x/places]
Size=32
Scale=2
Context=Places
Type=Fixed

[48x48/places]
Size=48
Scale=1
Context=Places
Type=Fixed

[48x48@2x/places]
Size=48
Scale=2
Context=Places
Type=Fixed

[64x64/places]
Size=64
Scale=1
Context=Places
Type=Fixed

[64x64@2x/places]
Size=64
Scale=2
Context=Places
Type=Fixed

[96x96/places]
Size=96
Scale=1
Context=Places
Type=Fixed

[128x128/places]
Size=128
Scale=1
Context=Places
Type=Fixed